#
# Focaltech 5626 touchscreen driver makefile
#

#obj-$(CONFIG_TOUCHSCREEN_FTS) += fts_ts.o 
#fts_ts-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_core.o focaltech_ctl.o focaltech_gesture.o #focaltech_flash.o 
#extlibs :=$(PWD)/drivers/input/touchscreen/ft_gesture_32bit_lib_v1.0_20140820.a 
#ldflagobj-$(CONFIG_TOUCHSCREEN_FTS) += fts_ts.o 
#obj-$(CONFIG_TOUCHSCREEN_FTS) +=--whole-archive $(extlibs) --no-whole-archive
#s-$(CONFIG_TOUCHSCREEN_FTS) +=--whole-archive $(extlibs) --no-whole-archive

obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_core.o focaltech_ctl.o focaltech_gesture.o focaltech_flash.o
